services:
  - type: web
    name: ecommerce-backend
    env: node
    buildCommand: npm install && npm rebuild bcrypt --build-from-source
    startCommand: node server-test.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
